
nombre1 = input(f"ingrese nombre del primer paciente: ")
peso1 = float(input(f"ingrese el peso: "))
estatura1 = float(input(f"ingrese el estatura: "))
edad1 = (input(f"ingrese el edad: "))
nombre2 = input(f"ingrese nombre del segundo paciente: ")
peso2 = float(input(f"ingrese el peso: "))
estatura2 = float(input(f"ingrese el estatura: "))
edad2 = (input(f"ingrese el edad: "))
nombre3 = input(f"ingrese nombre del tercer paciente: ")
peso3 = float(input(f"ingrese el peso: "))
estatura3 = float(input(f"ingrese el estatura: "))
edad3 = (input(f"ingrese el edad: "))
pacientes = ((nombre1,peso1,estatura1,edad1,nombre2,peso2,estatura2,edad2,nombre3,peso3,estatura3,edad3))
print (list(pacientes))
print (type(pacientes))